# Generated by Django 3.1.1 on 2020-09-12 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200912_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='points',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.1)]),
        ),
    ]
